---
- name: Set Docker
  import_tasks: prepare.yml

- name: Check if docker is installed
  stat: path="/usr/bin/docker"
  register: docker_check

- name: Check Version if docker is installed
  command: "docker version -f '{{ '{{' }}.Client.Version{{ '}}' }}'"
  register: get_docker_version
  ignore_errors: true
  when: docker_check.stat.isreg is defined

- name: minimum docker version if docker is installed
  fail:
    msg: >
          docker requires a minimum version of
          {{ docker_min_version }} on
          {{ ansible_distribution }}-{{ ansible_distribution_version }}
  when: docker_check.stat.isreg is defined and get_docker_version.stdout is version(docker_min_version, "<")

- name: Online install Docker if docker is not installed
  import_tasks: online.yml
  when: docker_check.stat.isreg is not defined

- name: Get Docker Version
  command: "docker version -f '{{ '{{' }}.Client.Version{{ '}}' }}'"
  register: installed_docker_version
  when: docker_check.stat.isreg is not defined

- name: Ensure docker service is started and enabled
  service:
    name: docker
    enabled: yes
    state: started
  ignore_errors: true

- name: Wait for docker
  command: "docker images"
  register: docker_ready
  retries: 10
  delay: 5
  until: docker_ready.rc == 0

- name: Check if custom tools is installed
  stat: path="/usr/local/bin/dps"
  register: custom_tools_check

- name: Install custom tools
  shell: "docker run --rm -v /usr/local/bin:/sysdir spanda/pkg tar zxf /pkg.tgz -C /sysdir"
  when: custom_tools_check.stat.isreg is not defined
