- name: Install docker online
  shell: "curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun"
  register: docker_task_result
  until: docker_task_result is succeeded
  retries: 4
  notify: restart docker